### ISSUE TITLE
mlp output for eps=0 (retrain, recons) not matching up with unattacked model

### ISSUE THREAD

**Issue by paullintilhac** [paullintilhac/cosc189-project#6]
I haven't actually looked at the recons output, but I assume there is the same problem there. I believe uttam was able to get this to work better on an older commit. Should at least be within a couple percentage points of the accuracy without an attack.

**Comment by uttam-rao** [comment]
Resolved now in the accuracy_fix branch. Error was that `X_test_orig -= mean` was commented out in the attack_wrapper().
